#!/bin/bash

c='--color=always'
gdf='--group-directories-first'

case $1 in
	'dirs'|'d')
		list='ls $c -dlth */';;
	'files'|'f')
		list='ls $c -plL | grep -v /';;
	'hidden'|'h')
		case $2 in
			'dirs'|'d')
				list='ls $c -dlth .??*/';;
			'files'|'f')
				list='ls $c -dplL .??* | grep -v /';;
			*)
				list='ls $c -dl $gdf .??*';;
		esac;;
	*)
		list='ls $c -hAlt $gdf';;
esac

eval $list
